name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    outputs:
      artifacts-path: ${{ steps.set-path.outputs.path }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24
      - name: Build binary
        run: |
          mkdir -p releases
          ext=""
          if [ "${{ matrix.os }}" == "windows" ]; then ext=".exe"; fi
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o releases/dsy-${{ matrix.os }}-${{ matrix.arch }}${ext} ./cmd/dsy
      - name: Set artifacts path
        id: set-path
        run: echo "::set-output name=path::releases/*"
      - name: Upload artifact for next job
        uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ matrix.os }}-${{ matrix.arch }}
          path: releases/*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download all binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries-linux-amd64
          path: releases/
      - uses: actions/download-artifact@v3
        with:
          name: binaries-linux-arm64
          path: releases/
      - uses: actions/download-artifact@v3
        with:
          name: binaries-darwin-amd64
          path: releases/
      - uses: actions/download-artifact@v3
        with:
          name: binaries-darwin-arm64
          path: releases/
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          artifacts: releases/*
          generateReleaseNotes: true
          makeLatest: true
          token: ${{ secrets.GH_TOKEN }}
